server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/www_csssnet_com
    username: www_csssnet_com
    password: 2Aw7p4S5p5GJSpBb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
girl:
  cupSize: B
  age: 18